package main

import "strings"

var (
	// Season 7 tiers, gets updated manually for now because no one reports this
	s7tiers = map[string]string{
		strings.ToLower("mudjoe2"):                 "Crystal",
		strings.ToLower("incnone"):                 "Crystal",
		strings.ToLower("RoyalGoof"):               "Crystal",
		strings.ToLower("Tufwfo"):                  "Crystal",
		strings.ToLower("Squega"):                  "Crystal",
		strings.ToLower("Staekk"):                  "Crystal",
		strings.ToLower("abu__yazan"):              "Crystal",
		strings.ToLower("cyber_1"):                 "Crystal",
		strings.ToLower("jackofgames"):             "Crystal",
		strings.ToLower("mayaundefined"):           "Crystal",
		strings.ToLower("pancelor"):                "Crystal",
		strings.ToLower("ptrevordactyl"):           "Crystal",
		strings.ToLower("spootybiscuit"):           "Crystal",
		strings.ToLower("moyuma"):                  "Obsidian",
		strings.ToLower("Revalize"):                "Obsidian",
		strings.ToLower("seanpwolf"):               "Obsidian",
		strings.ToLower("Siveure"):                 "Obsidian",
		strings.ToLower("supervillain_joe"):        "Obsidian",
		strings.ToLower("thedarkfreaack"):          "Obsidian",
		strings.ToLower("yuka34"):                  "Obsidian",
		strings.ToLower("kingtorture"):             "Obsidian",
		strings.ToLower("reijigazpacho"):           "Obsidian",
		strings.ToLower("bastet222"):               "Obsidian",
		strings.ToLower("biggiemac42"):             "Obsidian",
		strings.ToLower("call_me_kaye"):            "Obsidian",
		strings.ToLower("mantasmbl"):               "Obsidian",
		strings.ToLower("Paratroopa1"):             "Obsidian",
		strings.ToLower("ratata_ratata"):           "Obsidian",
		strings.ToLower("Ratracing"):               "Obsidian",
		strings.ToLower("raviolinguini"):           "Obsidian",
		strings.ToLower("arborelia"):               "Titanium",
		strings.ToLower("justsparkyyes"):           "Titanium",
		strings.ToLower("Uniowen"):                 "Titanium",
		strings.ToLower("Minhs2"):                  "Titanium",
		strings.ToLower("alex42918"):               "Titanium",
		strings.ToLower("Ancalagor"):               "Titanium",
		strings.ToLower("ARTQ"):                    "Titanium",
		strings.ToLower("chef_mayhem"):             "Titanium",
		strings.ToLower("cohomerlogist"):           "Titanium",
		strings.ToLower("definitely_not_him"):      "Titanium",
		strings.ToLower("Flygluffet"):              "Titanium",
		strings.ToLower("Lucoa"):                   "Titanium",
		strings.ToLower("Saakas"):                  "Titanium",
		strings.ToLower("SailorMint"):              "Titanium",
		strings.ToLower("tetel__"):                 "Titanium",
		strings.ToLower("WuffWuff"):                "Titanium",
		strings.ToLower("EpicSuccess"):             "Blood",
		strings.ToLower("MegaMissingn0"):           "Blood",
		strings.ToLower("yamiramiz"):               "Blood",
		strings.ToLower("cryss__"):                 "Blood",
		strings.ToLower("fiverfiverone"):           "Blood",
		strings.ToLower("professionaltwitchtroll"): "Blood",
		strings.ToLower("blacksenapi"):             "Blood",
		strings.ToLower("dsmidna"):                 "Blood",
		strings.ToLower("duneaught"):               "Blood",
		strings.ToLower("ekimekim"):                "Blood",
		strings.ToLower("firebrde"):                "Blood",
		strings.ToLower("Jamblar"):                 "Blood",
		strings.ToLower("Kailaria"):                "Blood",
		strings.ToLower("Kova46"):                  "Blood",
		strings.ToLower("Kyakh"):                   "Blood",
		strings.ToLower("rachelsatx"):              "Blood",
		strings.ToLower("Rotomington"):             "Blood",
		strings.ToLower("Slimo"):                   "Blood",
		strings.ToLower("wow_tomato"):              "Blood",
		strings.ToLower("Zinmo"):                   "Blood",
	}
	teamList = map[string][]string{
		"Dark Cookies": []string{
			"abu__yazan",
			"biggiemac42",
			"chef_mayhem",
			"Flygluffet",
			"incnone",
			"Jamblur",
			"JustSparkyYes",
			"Kova46",
			"Lucoa",
			"mantasMBL",
			"Megamissingn0",
			"Spootybiscuit",
			"WuffWuff",
		},
		"Frozen Cheese": []string{
			"arborelia",
			"bastet222",
			"dsmidna",
			"duneaught",
			"firebrde",
			"Kailaria",
			"moyuma",
			"Slimo",
			"Squega",
			"Staekk",
			"wow_tomato",
			"yamiramiz",
		},
		"Italian Carrots": []string{
			"ARTQ",
			"brumekuroi",
			"Cyber_1",
			"Minhs2",
			"mpr",
			"pancelor",
			"professionaltwitchtroll",
			"ratata_ratata",
			"Rachelsatx",
			"Revalize",
			"Siveure",
			"thedarkfreaaack",
			"yuka34",
		},
		"Regular Hams": []string{
			"alex42918",
			"Ancalagor",
			"Call_Me_Kaye",
			"definitely_not_HIM",
			"EpicSuccess",
			"JackOfGames",
			"mudjoe2",
			"Paratroopa1",
			"ptrevortactyl",
			"Rotomington",
			"saakas0206",
			"seanpwolf",
			"uniowen",
			"Zin",
		},
		"Stinkin' Rebels": []string{
			"cryss__",
			"ekimekim",
			"fiverfiverone",
			"KingTorture",
			"mayaundefined",
			"Ratracing",
			"reijigazpacho",
			"RoyalGoof",
			"sailormint",
			"supervillain_joe",
			"tetel",
			"Tufwfo",
		},
	}
)
